[package]
name = "quadratic-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
js-sys = "0.3.60"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"

arrow2 = { version = "0.14", features = [
  "io_ipc",
  "io_parquet",
  "io_parquet_gzip",
  "io_parquet_brotli",
  "io_csv"
] }
parquet2 = { version = "0.16", default_features = false, optional = false }

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response'
]


